# Site settings
title: "Kingdom Builders"
subtitle: "Serving and growing the Kingdom of God with every tool, skill, and opportunity available to us."
email: hello@kingdombuilders.io
description:  "A Slack Community for Technology in Missions and Ministry"
url: "http://kingdombuilders.io"
title_image: 'logo.png'
title_description:   "A Slack Community for Technology in Missions and Ministry"
github_repository: https://github.com/kingdombuilders/kingdombuilders.github.io

# Social usernames/URLs
twitter_username: hey_kb_mm
github_username:  kingdombuilders
slack_link:       http://kbmm.slack.com
contact_email:    hello@kingdombuilders.io
disqus_account:   kingdombuilders

# Footer
footer_left: "Site theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# For RSS
name: Kingdom Builders
description: A Slack Community for Technology in Missions and Ministry
url: http://kingdombuilders.io/
